### ISSUE TITLE
[BUG] <Follow,Followers>

### ISSUE THREAD

**Issue by AhmedKarray005** [thecyberworld/TheCyberHUB#640]
### Describe the bug

I encountered an issue while using the project. Upon clicking the "Follow" button, the action doesn't proceed unless I refresh the page, as demonstrated in the attached video. Additionally, there seems to be a discrepancy with the displayed number of followers, also visible in the video.

### To Reproduce

1-click on any profile
2-click on follow button 
3-refresh the page and you'll see the visual change

### Expected Behavior

The expected behavior is that when I click the "Follow" button, the action should be executed immediately without requiring a page refresh. Similarly, the displayed number of followers should accurately reflect the current count without any discrepancies.

### Screenshot/ Video

https://github.com/thecyberworld/TheCyberHUB/assets/104280658/87776cf8-d413-495a-8a5a-24c59612d5ec

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@AhmedKarray005 hmm, weird,  I fixed it  3 days ago. Did you sync the last updates and pulled them? When did you clone the project?

**Comment by ArkadiK94** [comment]
Yeah, your local code is not updated,  I can tell because the way buttons display,  it was changed. 
https://github.com/thecyberworld/TheCyberHUB/pull/637

Anyway, thanks for checking it up. However, please,  first sync the updates in you forked repo -> git checkout dev -> git pull.
Then try and find any other bugs , if you will encounter any , feel free to open related issues :)
I am closing this one.
