### ISSUE TITLE
[BUG] Frontend Layout issue-Navbar Dropdowns Overlap 

### ISSUE THREAD

**Issue by Som401** [thecyberworld/TheCyberHUB#641]
### Describe the bug

The frontend layout of the website currently has a problem where the dropdown menus in the navbar overlap. Specifically, when the navbar dropdown menu is expanded to show its content, and then the user clicks on their profile picture to access its dropdown menu, the profile dropdown menu gets covered by the navbar dropdown. This results in a poor user experience as users may have difficulty accessing the profile dropdown options.

### To Reproduce

1)Expand the navbar dropdown menu.
2)Click on the profile picture to access the profile dropdown menu.

### Expected Behavior

The profile dropdown menu should appear above the navbar dropdown menu, ensuring that all dropdown menus are accessible and do not overlap.

### Screenshot/ Video

https://github.com/thecyberworld/TheCyberHUB/assets/147496504/2ef53b73-bc0d-42c2-91ce-47c5920bbc4c

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
Thanks for checking it up. However, please, first sync the updates in you forked repo -> git checkout dev -> git pull.
Then you will see that this bug was already fixed and merged :)

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/94c302dc-995a-40dc-8757-b9973f56d82c

Still you can try and find any other bugs after you will sync , if you will encounter any , feel free to open related issues :)
I am closing this one.
